<a href="https://colab.research.google.com/github/jorgemdj/Perceptron-Network/blob/main/Perceptron_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_excel('/content/Tabela#Seção3.6_RNA.xls')

In [27]:
#setting entrance parameters

entrance = np.array(data.drop('d', axis=1))
exit = np.array(data.drop(['x1','x2','x3'], axis=1))

In [28]:
#addding a [-1] collumn to X sheets to use W[0] as a random limiar activation as a sum of other random determined numbers W[i]+...+W[n]

X = np.hstack((np.ones_like(exit)*(-1),entrance))
Y = exit

input_neurons = X.shape[1]
output_neurons = 1

#adding seed to analyze results
np.random.seed(12)
W = np.random.random_sample((output_neurons,input_neurons)).T
print(W)

[[0.15416284]
 [0.7400497 ]
 [0.26331502]
 [0.53373939]]


In [29]:
def perceptron(x, y, z, learning_rate):

  #Response Vector
  ycaret_vec = np.zeros_like(Y)


  epoch = 0
  E = True

  while E == True:
    for i in range(0, x.shape[0]):

      #Summation Input Data:
      f = np.dot(x[i], W)

      #Conditional Activation Function (Bipolar Step):
      if f > z:
        ycaret_vec[i] = 1
      else:
        ycaret_vec[i] = -1

      #Updating of weights:
      if ycaret_vec[i] != Y[i]:
        for j in range(0, len(W)):
          W[j] = W[j] + learning_rate*(y[i] - ycaret_vec[i])*x[i][j]

      else: continue

    epoch += 1

    error = 0

    #Accounting for errors:
    for i in range(0, Y.shape[0]):
        if ycaret_vec[i] != Y[i]:
          error += 1
        else: continue

    if error == 0:
      E = False

    #Custom Output:
    elif int((epoch)%(15)) == 0:
        print(f'Epoch:  [{epoch}] error: {error} / {Y.shape[0]} [{100*error/Y.shape[0]:.2f}% ]')

    else: continue


  #Check final results:
  return W.T, epoch



In [30]:
x=X
y=Y
z=0
learning_rate = 0.01


perceptron(x, y, z, learning_rate)

Epoch:  [15] error: 12 / 30 [40.00% ]
Epoch:  [30] error: 12 / 30 [40.00% ]
Epoch:  [45] error: 8 / 30 [26.67% ]
Epoch:  [60] error: 7 / 30 [23.33% ]
Epoch:  [75] error: 5 / 30 [16.67% ]
Epoch:  [90] error: 5 / 30 [16.67% ]
Epoch:  [105] error: 7 / 30 [23.33% ]
Epoch:  [120] error: 9 / 30 [30.00% ]
Epoch:  [135] error: 5 / 30 [16.67% ]
Epoch:  [150] error: 5 / 30 [16.67% ]
Epoch:  [165] error: 5 / 30 [16.67% ]
Epoch:  [180] error: 6 / 30 [20.00% ]
Epoch:  [195] error: 4 / 30 [13.33% ]
Epoch:  [210] error: 4 / 30 [13.33% ]
Epoch:  [225] error: 6 / 30 [20.00% ]
Epoch:  [240] error: 3 / 30 [10.00% ]
Epoch:  [255] error: 6 / 30 [20.00% ]
Epoch:  [270] error: 5 / 30 [16.67% ]
Epoch:  [285] error: 6 / 30 [20.00% ]
Epoch:  [300] error: 2 / 30 [6.67% ]
Epoch:  [315] error: 6 / 30 [20.00% ]
Epoch:  [330] error: 3 / 30 [10.00% ]


(array([[-2.90583716,  1.4278137 ,  2.39816502, -0.67725061]]), 336)

In [31]:
#Validation:

test = pd.read_excel('/content/Tabela#3.3_RNA.xls')

#Adding [-1] collumn as the training set
entrance_test = np.array(test)
X_test = np.hstack((np.ones((entrance_test.shape[0],1))*(-1),entrance_test))

#Getting W from the training
W_test = np.copy(W)
W_test

array([[-2.90583716],
       [ 1.4278137 ],
       [ 2.39816502],
       [-0.67725061]])

In [32]:
#Answers:

def matrix_bipolar_step(z: np.ndarray):
  for i in range(z.shape[0]):
    for j in range(z.shape[1]):
      if z[i,j]>= 0:
        z[i,j] = 1
      else:
        z[i,j] = -1
  return z

Y_test = np.dot(X_test,W_test)
matrix_bipolar_step(Y_test)

array([[-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.]])