<a href="https://colab.research.google.com/github/jorgemdj/Perceptron-Network/blob/main/Perceptron_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_excel('/content/Tabela#Seção3.6_RNA.xls')

In [2]:
#setting entrance parameters

entrance = np.array(data.drop('d', axis=1))
exit = np.array(data.drop(['x1','x2','x3'], axis=1))

In [48]:
#addding a [-1] collumn to X sheets to use W[0] as a random limiar activation as a sum of other random determined numbers W[i]+...+W[n]

X = np.hstack((np.ones_like(exit)*(-1),entrance))
Y = exit

input_neurons = X.shape[1]
output_neurons = 1

#adding seed to analyze results
np.random.seed(12)
W = np.random.random_sample((output_neurons,input_neurons)).T
print(W)

[[0.15416284]
 [0.7400497 ]
 [0.26331502]
 [0.53373939]]


In [49]:
def perceptron(x, y, z, learning_rate, t):

  #Response Vector
  ycaret_vec = np.zeros_like(Y)


  epoch = 0

  while epoch < t:
    for i in range(0, x.shape[0]):

      #Summation Input Data:
      f = np.dot(x[i], W)

      #Conditional Activation Function (Bipolar Step):
      if f > z:
        ycaret_vec[i] = 1
      else:
        ycaret_vec[i] = -1

      #Updating of weights:
      if ycaret_vec[i] != Y[i]:
        for j in range(0, len(W)):
          W[j] = W[j] + learning_rate*(y[i] - ycaret_vec[i])*x[i][j]

      else: continue

    epoch += 1

    error = 0

    #Accounting for errors:
    for i in range(0, Y.shape[0]):
        if ycaret_vec[i] != Y[i]:
          error += 1
        else: continue

    #Custom Output:
    if int((epoch)%(t/15)) == 0:
        print(f'Epoch:  [{epoch} / {t}] error: {error} / {Y.shape[0]} [{100*error/Y.shape[0]:.2f}% ]')


  #Check final results:
  return W.T, ycaret_vec.T, Y.T



In [50]:
x=X
y=Y
z=0
learning_rate = 0.01
t=350


perceptron(x, y, z, learning_rate, t)

Epoch:  [24 / 350] error: 10 / 30 [33.33% ]
Epoch:  [47 / 350] error: 7 / 30 [23.33% ]
Epoch:  [70 / 350] error: 7 / 30 [23.33% ]
Epoch:  [94 / 350] error: 8 / 30 [26.67% ]
Epoch:  [117 / 350] error: 5 / 30 [16.67% ]
Epoch:  [140 / 350] error: 5 / 30 [16.67% ]
Epoch:  [164 / 350] error: 8 / 30 [26.67% ]
Epoch:  [187 / 350] error: 3 / 30 [10.00% ]
Epoch:  [210 / 350] error: 4 / 30 [13.33% ]
Epoch:  [234 / 350] error: 7 / 30 [23.33% ]
Epoch:  [257 / 350] error: 6 / 30 [20.00% ]
Epoch:  [280 / 350] error: 8 / 30 [26.67% ]
Epoch:  [304 / 350] error: 6 / 30 [20.00% ]
Epoch:  [327 / 350] error: 2 / 30 [6.67% ]
Epoch:  [350 / 350] error: 0 / 30 [0.00% ]


(array([[-2.90583716,  1.4278137 ,  2.39816502, -0.67725061]]),
 array([[-1, -1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1,
          1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1]]),
 array([[-1, -1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1,
          1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1]]))

In [51]:
#Validation:

test = pd.read_excel('/content/Tabela#3.3_RNA.xls')

#Adding [-1] collumn as the training set
entrance_test = np.array(test)
X_test = np.hstack((np.ones((entrance_test.shape[0],1))*(-1),entrance_test))

#Getting W from the training
W_test = np.copy(W)
W_test

array([[-2.90583716],
       [ 1.4278137 ],
       [ 2.39816502],
       [-0.67725061]])

In [56]:
#Answers:

def matrix_bipolar_step(z: np.ndarray):
  for i in range(z.shape[0]):
    for j in range(z.shape[1]):
      if z[i,j]>= 0:
        z[i,j] = 1
      else:
        z[i,j] = -1
  return z

Y_test = np.dot(X_test,W_test)
matrix_bipolar_step(Y_test)

array([[-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.]])